openapi: 3.0.3
info:
  title: SWAssistant Backend
  version: v0.1.0
components:
  schemas:
    Editable:
      type: object
      description: Fields on editables so they can use this Backend
      additionalProperties: true
      properties:
        _id:
          type: string
        owner:
          type: string
          description: ID of the user
        type:
          type: integer
          description: 0 - Character, 1 - Minion, 2 - Vehicle
        lastMod:
          type: integer
          description: Unix time of last edit.
        perm:
          type: array
          items:
            $ref: "#/components/schemas/EditablePerm"
    EditableSync:
      type: object
      description: Minimal fields to know if data (and which data) needs to be synced.
      required:
        - _id
        - lastMod
      properties:
        _id:
          type: string
        type:
          type: integer
          description: 0 - Character, 1 - Minion, 2 - Vehicle
        lastMod:
          type: integer
          description: Unix time of last edit.
    EditablePerm:
      type: object
      description: Permissions for an editable
      properties:
        name:
          type: string
          description: Username or Room UUID 
        room:
          type: boolean
          description: Is this a reference to a room (as opposed to a user)
        write:
          type: boolean
          description: Can this user (or users in this room) make edits to this editable. If false, users are RO.
    RoomInv:
      type: object
      description: A room invited
      properties:
        _id:
          type: string
        name:
          type: string
        owner:
          type: string
          description: Username of owner
    Room:
      type: object
      description: A room of shared editables
      properties:
        _id:
          type: string
          description: UUID of room
        name:
          type: string
        owner:
          type: string
          description: Username of owner
        users:
          type: array
          description: Usernames of users
          items:
            type: string
        invites:
          type: array
          nullable: true
          description: Sent invites. Only sent to owner.
          items:
            type: string
        declined:
          type: array
          nullable: true
          description: Declined invites. Only sent to owner.
          items:
            type: string
        editables:
          type: array
          description: Editable UUIDs that are in this room. Not stored, but calculated.
          items:
            type: string
  parameters:
    Key:
      name: key
      description: API Key
      required: true
      in: query
      schema:
        type: string
    Token:
      name: token
      description: User access token
      required: true
      in: query
      schema:
        type: string
paths:
  /editable:
    get:
      description: Get info about your editables
      parameters:
        - $ref: "#/components/parameters/Key"
        - $ref: "#/components/parameters/Token"
      responses:
        '200':
          description: List of your editables in sync format
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EditableSync"
  /editable/{uuid}:
    post:
      description: Upload a new or update an existing editable
      parameters:
        - $ref: "#/components/parameters/Key"
        - $ref: "#/components/parameters/Token"
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Editable successfully updated
        '201':
          description: Editable successfully created
        '204':
          description: Invalid UUID
    delete:
      description: Delete an editable
      parameters:
        - $ref: "#/components/parameters/Key"
        - $ref: "#/components/parameters/Token"
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted
        '204':
          description: Invalid UUID
    get:
      description: Get an editable
      parameters:
        - $ref: "#/components/parameters/Key"
        - $ref: "#/components/parameters/Token"
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Returns the editable requested.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Editable"
        '204':
          description: Invalid UUID
  /editable/{uuid}/sync:
    get:
      description: Get sync info about a particular editable
      parameters:
        - $ref: "#/components/parameters/Key"
        - $ref: "#/components/parameters/Token"
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Get sync info about a particular profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EditableSync"
        '204':
          description: Invalid UUID
  /rooms:
    description: List of rooms you have access to
    get:
      parameters:
        - $ref: "#/components/parameters/Key"
        - $ref: "#/components/parameters/Token"
      responses:
        '200':
          description: Get your rooms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Room"
  /rooms/invites:
    description: List of room invites.
    get:
      parameters:
        - $ref: "#/components/parameters/Key"
        - $ref: "#/components/parameters/Token"
      responses:
        '200':
          description: List of rooms you are invited to.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RoomInv"
  /rooms/invites/{uuid}:
    description: Accept or refuse an invite
    post:
      parameters:
        - $ref: "#/components/parameters/Key"
        - $ref: "#/components/parameters/Token"
        - name: accept
          in: query
          required: true
          schema:
            type: boolean
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Room invite accepted or refused.
        '204':
          description: Invalid UUID
  /rooms/create:
    description: Create a new room
    post:
      parameters:
        - $ref: "#/components/parameters/Key"
        - $ref: "#/components/parameters/Token"
      responses:
        '201':
          description: Room created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Room"
  /rooms/{uuid}:
    get:
      parameters:
        - $ref: "#/components/parameters/Key"
        - $ref: "#/components/parameters/Token"
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Returns info about room
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Room"
        '204':
          description: Invalid UUID
    delete:
      description: Delete a room. Only owners can do this.
      parameters:
        - $ref: "#/components/parameters/Key"
        - $ref: "#/components/parameters/Token"
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted
        '204':
          description: Invalid UUID

                